version: "3.9"

services:
  app:
    build: .
    container_name: mi-app-java
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mibasedatos
      SPRING_DATASOURCE_USERNAME: miusuario
      SPRING_DATASOURCE_PASSWORD: miclave
    ports:
      - "8080:8080"
